<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cadastro</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="style.css">

  <?php
  if (isset($_SESSION['usuario'])) {
    $usuario = $_SESSION["usuario"];
    $_SESSION["usuario"] = '';
  }
  if (isset($_SESSION['imoveis'])) {
    $imoveis = $_SESSION["imoveis"];
    $_SESSION["imoveis"] = '';
  }
  ?>
  
</head>
<body>

<header class="">
<div class="cabeçalho">
            <a href="inicio">
                <img class="imgcabecalho" src="img/logo.png" alt="logo">
            </a>
            <div class="cabeçalho_1">
                <h3 class="fw-bold textocaabecalho">BRINDES E MIMOS</h3>
            </div>
        </div>
        <nav>
            <div class="float-end me-md-5 me-2 position-absolute" style="top:0;right: 0;margin-top: 50px;margin-left: 10px;">
                <a href=" https://wa.me/5575999339915" target="_blank"><img src="img/whats.png" height="35" width="35" alt="Whatsapp"></a>
                <a  class="ms-2" href="https://www.instagram.com/" target="_blank"><img src="img/insta.png" height="35" width="35" alt="Instagram"></a>
                <a  class="ms-2" href="https://pt-br.facebook.com/" target="_blank"><img src="img/face.png" height="35" width="35" alt="Facebook"></a>
            </div>
        </nav>
  </header>

  <div class="d-flex justify-content-center mt-3">
    <h1 style="color: rgb(116, 194, 0);"> <?php echo $usuario ?? '' ?> </h1>
    <h1 style="color: rgb(116, 194, 0);"> <?php echo $imoveis ?? '' ?> </h1>
  </div>

<div class="rounded p-md-3 p-2">
<div class="d-flex justify-content-center p-2 mb-3">
  <h2 class="fw-bold text-decoration-underline">Cadastrar Card</h2>
</div>

<div class="d-flex justify-content-center">
<form class="row g-3  col-12 col-md-7 p-md-2 rounded" action="cadastroImovelController" method="post" enctype="multipart/form-data" style="background-color: #b2cbc0;justify-content: center;">
    
      <div class="col-8">
        <label class="form-label fw-bold" for="titulo">Título</label><br>
          <input class="form-control" id="titulo" name="titulo" type="text" required>
        </div>

        <div class="col-8">
        <label class="form-label fw-bold" for="descricao">Descrição</label><br>
          <textarea class="form-control" id="descricao" name="descricao" type="text" required></textarea>
        </div>

        <div class="col-8 mt-4">
          <label class="form-label fw-bold" for="descricao">Escolha um arquivo</label><br>
          <div class="input-group">
            <input type="file" class="form-control" id="media" name="media" accept="video/*,image/*" aria-describedby="inputGroupFileAddon04" aria-label="Upload" required>
          </div>
        </div>

        <div class="col-8">
        <label class="form-label fw-bold" for="descricao">Escolha a área</label><br>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="secao" id="inlineRadio1" value="tutoriais" checked>
            <label class="form-check-label" for="inlineRadio1">Tutoriais</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="secao" id="inlineRadio2" value="revenda">
            <label class="form-check-label" for="inlineRadio2">Revenda</label>
          </div>
          <!-- <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="secao" id="inlineRadio3" value="beleza">
            <label class="form-check-label" for="inlineRadio3">Beleza</label>
          </div> -->
        </div>

        <div class="col-8">
        <label class="form-label fw-bold" for="link">Link (YouTube ou Shopee)</label><br>
          <input class="form-control" id="link" name="link" type="text" required>
        </div>

    <div class="mt-4 mb-3 d-flex justify-content-center">
      <button class="btn btn-primary w-md-25" type="submit">Cadastrar Conteúdo</button>
    </div>
</form>
</div>
</div>

<!-- -------------------------------------------------------------------------------------------- -->

<div class="mt-md-5 rounded p-3">
<div class="d-flex justify-content-center p-2 mb-3">
  <h2 class="fw-bold text-decoration-underline">Cadastrar Usuário</h2>
</div>

<div class="d-flex justify-content-center">
<form class="row g-3 col-md-6 p-2 rounded" action="cadastroUsuarioController" method="post" style="background-color: #b2cbc0;">

<div class="col-md-6">
  <label class="form-label fw-bold" for="nome">Nome Completo</label><br>
    <input class="form-control" id="nome" name="nome" type="text" required>
  </div>

  <div class="col-md-6">
    <label class="form-label fw-bold" for="email">Email</label><br>
    <input class="form-control" id="email" name="email" type="email" required>
  </div>

  <div class="col-md-6">
    <label class="form-label fw-bold" for="senha">Senha</label><br>
    <input class="form-control" id="senha" name="senha" type="password" required>
  </div>
  <div class="col-md-6">
    <label class="form-label fw-bold" for="confirmarsenha">Confirmar Senha</label><br>
    <input class="form-control" id="confirmarsenha" type="password" required>
  </div>
  <div class="mt-2 mb-2 d-flex justify-content-center">
  <button class="btn btn-warning w-md-25 mt-4" type="submit" onclick="return validarSenha()">Cadastrar Usuário</button>
</div>
</form>
</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script>
let senha = document.getElementById('senha');
    let confirmarsenha = document.getElementById('confirmarsenha');
    
    function validarSenha() {
      if (senha.value != confirmarsenha.value) {
        confirmarsenha.setCustomValidity("Senhas diferentes!");
        confirmarsenha.reportValidity();
        return false;
      } else {
        confirmarsenha.setCustomValidity("");
        return true;
      }
  }
   
  function checarImagens() {
    if (imagem01.files[0] && imagem02.files[0] && imagem03.files[0] && imagem04.files[0] && imagem05.files[0]) {
      return true;
    } else {
      alert('Todas as imagens são obrigatórias!');
      return false;
    }
  }

  let dispositivo = 'pc';
  function mudarimagem(val, device) {
    if (device == 'mobile') {
      dispositivo = 'mobile';
    }
    document.getElementById(`imagem0${val}`).click();
  }

  function imagemprevia(val) {
    let previa;
    const img = document.getElementById(`imagem0${val}`).files[0];
    
    if (dispositivo == 'mobile') {
      previa = document.getElementById(`previa00${val}`);
    } else {
      previa = document.getElementById(`previa0${val}`);
    }
    const url = URL.createObjectURL(img);
    previa.src = url;
  }
</script>
  
</body>
</html>