<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cadastro</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="style.css">
  
</head>
<body>
<?php
  if (isset($_SESSION['message'])) {
    $message = $_SESSION["message"];
    $_SESSION["message"] = '';
  }
?>

<header class="">
      <div class="cabeçalho">
            <a href="inicio">
                <img class="imgcabecalho" src="img/logo.png" alt="logo">
            </a>
            <div class="cabeçalho_1">
                <h3 class="fw-bold textocaabecalho">BRINDES E MIMOS</h3>
            </div>
        </div>
        <nav>
            <div class="float-end me-md-5 me-2 position-absolute" style="top:0;right: 0;margin-top: 50px;margin-left: 10px;">
                <a href=" https://wa.me/5575999339915" target="_blank"><img src="img/whats.png" height="35" width="35" alt="Whatsapp"></a>
                <a  class="ms-2" href="https://www.instagram.com/" target="_blank"><img src="img/insta.png" height="35" width="35" alt="Instagram"></a>
                <a  class="ms-2" href="https://pt-br.facebook.com/" target="_blank"><img src="img/face.png" height="35" width="35" alt="Facebook"></a>
            </div>
        </nav>
  </header>
    <!-- --------------------------------------------------------------------------------------------------------------------------- -->

<div class="mt-md-5 rounded p-3">
  <div class="d-flex justify-content-center p-2 mb-3">
    <h2 class="fw-bold text-decoration-underline">Acessar Conta</h2>
  </div>

  <div class="d-flex justify-content-center">
    <form class="row g-3 col-md-6 p-2 rounded" action="loginController" method="post" style="background-color: #b2cbc0;">

      <div class="col-md-6">
        <label class="form-label fw-bold" for="email">Email</label><br>
        <input class="form-control" id="email" name="email" type="email" required>
      </div>

      <div class="col-md-6">
        <label class="form-label fw-bold" for="senha">Senha</label><br>
        <input class="form-control" id="senha" name="senha" type="password" required>
      </div>

      <div class="mt-2 mb-2 d-flex justify-content-center">
      <button class="btn btn-warning w-md-25 mt-4" type="submit">Entrar</button>
    </div>
    </form>
  </div>
</div>

<div class="d-flex justify-content-center p-2 mb-3">
    <h2 class="fw-bold"><?php echo $message ?? '' ?></h2>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  
</body>
</html>